language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: marskar
  password:
    secure: E4PDsVpNnlA8HEPcwvpgAiLsiASJI2qqAAj0XpfYkJXPvN2gFHfx6AlZt539cObMgw0PaA5TrQzVqqFXFuJqwW9ty1NlkeF0Q4YM664E5dQ7neuTVb/B/K/pFdv3+IDGV1Wy9CfdiO2gOa5t+bQzNxD08/ZttF2vtwMmdnDdihAKQ/65qdEgG+FuyyK3D5pYvjXPL02yKg/eXL5dGznnz/yUSdpFiBgG2AuRUsPxq4C18ZUvvPkQxnMG/UA/6Uu31rsL372weYxz7hNJSRxBn9fCpn9Jie+etSCy/ScGLgWGmZB8olLoJRtuBsVTQfFqUKEz0jyZHCxg231goP1l0LHbKp76ev0Wjr/V2vJNGJTEXbQyzVe/iU1eqhY5/1MQBWU7gfhhoT2LkX4lDWoGcdIAMwMCFshq6HYe9GIufJhTBjm5anoyLCaC0m0dUEjVikPIvVdvOpHRATcDZlaefjwFwcS7uV2/j2AUNcRcwrFFxchCswB5iICsTJ/g+TAF6qS1V0RQcwDWIyn6yALqYKlQiXC3LG3a4at698hXZZcQU9sTteItd+T2Ll4sAjTsdAuG1cZUgEZh0RnLoRIYKrnYu52MdSfWMTxiVcqU04MU/z4VGc+hle8rJzzKRFpy7TaKnmL+5IwDSsERdnrwWQixGe3vQvS/KL0SNj2gycA=
  on:
    tags: true
    repo: marskar/slidoc
    python: 3.6
